//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class JudgeChooseWord extends JPanel {
    private JButton btnStart;
    private JTextField txtWord;
    private JLabel lblWord;
    private JList lstParticipants;

    public JudgeChooseWord() {
        //construct preComponents
        String[] lstParticipantsItems = {"Waiting for participants ..."};

        //construct components
        btnStart = new JButton ("Start game!");
        btnStart.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        //scheduler.addToQueueLast(button.getText());
                        System.out.println("Button pressed");
                    }
                });
        txtWord = new JTextField (5);
        lblWord = new JLabel ("Write your word:");
        lstParticipants = new JList (lstParticipantsItems);

        //adjust size and set layout
        setPreferredSize (new Dimension (266, 293));
        setLayout (null);

        //add components
        add (btnStart);
        add (txtWord);
        add (lblWord);
        add (lstParticipants);

        //set component bounds (only needed by Absolute Positioning)
        btnStart.setBounds (5, 240, 255, 50);
        txtWord.setBounds (5, 185, 260, 25);
        lblWord.setBounds (5, 160, 100, 25);
        lstParticipants.setBounds (5, 5, 255, 140);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("JudgeChooseWord");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new JudgeChooseWord());
        frame.pack();
        frame.setVisible (true);
    }
}
