//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!


import java.awt.*;
import java.awt.event.*;
import java.text.NumberFormat;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.NumberFormatter;
import javax.swing.plaf.FontUIResource;

public class JudgeChooseWord extends JPanel {
    private JButton btnStart;
    private JTextField txtWord;
    private JLabel lblWord;
    public JList lstParticipants;
    private JLabel lblTime;
    private JFormattedTextField txtTime;
   
    private UIActionHandler actionHandler;

    public JudgeChooseWord(UIActionHandler handler) {
        this.actionHandler = handler;
        UIManager.put("Label.font", new FontUIResource(new Font("Dialog", Font.PLAIN, 20)));
    
        //construct preComponents
        String[] lstParticipantsItems = {"Waiting for participants ..."};

        //construct components
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        formatter.setAllowsInvalid(false);
        // If you want the value to be committed on each keystroke instead of focus lost
        formatter.setCommitsOnValidEdit(true);
        txtTime = new JFormattedTextField(formatter);

        btnStart = new JButton ("Start game!");
        btnStart.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        String word = txtWord.getText();
                    	int drawingTime = Integer.parseInt(txtTime.getText());
                    	
                    	System.out.println("Judge selected '" + word + "'. Drawing time " + drawingTime + " s");
                    	
                    	// send word and drawingTime to scheduler
                        //scheduler.addToQueueLast(...);
                        actionHandler.judgeSendWord(word);
                    }
                });
        txtWord = new JTextField (5);
        lblWord = new JLabel ("Write your word:");
        lstParticipants = new JList (lstParticipantsItems);
        lblTime = new JLabel ("Time (s):");

        //adjust size and set layout
        setPreferredSize (new Dimension (265, 324));
        setLayout (null);

        //add components
        add (btnStart);
        add (txtWord);
        add (lblWord);
        add (lstParticipants);
        add (lblTime);
        add (txtTime);

        //set component bounds (only needed by Absolute Positioning)
        btnStart.setBounds (5, 240, 255, 50);
        txtWord.setBounds (5, 185, 260, 25);
        lblWord.setBounds (5, 160, 300, 25);
        lstParticipants.setBounds (5, 5, 255, 140);
        lblTime.setBounds (5, 225, 100, 25);
        txtTime.setBounds (110, 225, 150, 25);
        
        txtTime.setText("30");
    }

}

/*
    public static void main (String[] args) {
        JFrame frame = new JFrame ("JudgeChooseWord");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new JudgeChooseWord());
        frame.pack();
        frame.setVisible (true);
    }
}
*/