//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!


import java.awt.*;
import java.awt.event.*;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.plaf.FontUIResource;

public class JudgeWaiting extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    
    private Timer countdownTimer = new Timer();
    int secondsLeft = 0;    


    public JudgeWaiting() {
    	UIManager.put("Label.font", new FontUIResource(new Font("Dialog", Font.PLAIN, 20)));
    	
        //construct components
        jcomp1 = new JLabel ("Participants are drawing ...");
        jcomp2 = new JLabel ("Time (s): ");
        jcomp3 = new JLabel ("XX s");

        //adjust size and set layout
        setPreferredSize (new Dimension (285, 125));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (20, 10, 250, 50);
        jcomp2.setBounds (20, 70, 100, 25);
        jcomp3.setBounds (120, 70, 100, 25);
    }
    
    public void startCountdown(int drawingTime) {
    	secondsLeft = drawingTime + 1;
    	TimerTask task = new TimerTask() {
            public void run() {
            	secondsLeft--;
            	jcomp3.setText(secondsLeft + " s");
            	
            	if(secondsLeft <= 0) {
                	countdownTimer.cancel();
                	countdownTimer.purge();
            	}
            }
        };
    	countdownTimer.scheduleAtFixedRate(task, 0, 1000);
    }
    public void startCountdown() {
    	startCountdown(10);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Drawing Game: Waiting");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        JudgeWaiting j = new JudgeWaiting();
        frame.getContentPane().add (j);
        frame.pack();
        frame.setVisible (true);
        
        j.startCountdown();
    }
}
